# _config.yml
title: HeatmapByDM
baseurl: "/HeatmapByDM"
url: "https://traqstar.github.io"
theme: jekyll-theme-minimal

# Author settings
author:
  name: Kevin Kuhn

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md