# Site settings
title: HeatmapByDM
baseurl: "/HeatmapByDM"
url: "https://traqstar.github.io"

# Theme settings
remote_theme: niklasbuschmann/contrast
theme_colors:
  background: "#ffffff"
  text: "#333333"
  link: "#4CAF50"

# Author settings
author:
  name: Kevin Kuhn

# Build settings
markdown: kramdown
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .git
  - README.md